### ISSUE TITLE
Reporting Period errors with 07_reporting_periods.js

### ISSUE THREAD

**Issue by eschwein-usds** [usdigitalresponse/cares-reporter#216]
https://github.com/usdigitalresponse/cares-reporter/blob/master/seeds/07_reporting_periods.js

The reporting_periods script is missing the field "CRF End Date".  This does not cause issues in setup, but throws an error when attempting to upload a file.  The error appears to the user as "500 Internal Server error" with no other information.  Adding the field to the seed script would solve this.

Additionally, the file should be renamed so that is is loaded before 05_app_settings.js.  Otherwise 05_app_settings.js will not run and throws an error.  Once I renamed it to "04_reporting_periods.js", the seeding went fine.

Logs from the server console:
```
POST /api/uploads
Filename: 123-2000395777-09302020-v1.xlsx size: 2099169
192.168.7.68 - - [03/Mar/2021:23:24:06 +0000] "POST /api/uploads HTTP/1.1" 500 763
RangeError: Invalid time value
    at format (/Users/Beth/cares-reporter/node_modules/date-fns/format/index.js:390:11)
    at validateData (/Users/Beth/cares-reporter/src/server/services/validate-data/index.js:29:19)
    at validateUpload (/Users/Beth/cares-reporter/src/server/services/validate-upload.js:83:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async processUpload (/Users/Beth/cares-reporter/src/server/services/process-upload.js:39:7)
    at async /Users/Beth/cares-reporter/src/server/routes/uploads.js:37:33
```

Happy to prepare a Pull Request to fix these.

**Comment by Michael-Stanford** [comment]
Thanks! Please prepare a PR for these and set me and Larry as reviewers.
Best,
Michael.

**Comment by bethlogic** [comment]
Related, once you have more data in the database, running the seed command (yarn knex seed:run) returns an error because it cannot delete the users from that table because of the foreign key reference on uploads (there may be more).  I got around it by dropping the database and re-creating it.

```
Error: Error while executing "/Users/Beth/cares-reporter/seeds/02_users.js" seed: delete from "users" where "role" = $1 - update or delete on table "users" violates foreign key constraint "uploads_user_id_foreign" on table "uploads"
    at Seeder._waterfallBatch (/Users/Beth/cares-reporter/node_modules/knex/lib/seed/Seeder.js:146:23)
error: delete from "users" where "role" = $1 - update or delete on table "users" violates foreign key constraint "uploads_user_id_foreign" on table "uploads"
    at Parser.parseErrorMessage (/Users/Beth/cares-reporter/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/Beth/cares-reporter/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/Beth/cares-reporter/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/Beth/cares-reporter/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
error Command failed with exit code 1.
```
